### ISSUE TITLE
Create a /docs/ folder and move all documentation there

### ISSUE THREAD

**Issue by jithinbp** [fossasia/pslab-desktop#107]
At present, experiment specific helpfiles are located in psl_res/HTML/ , and these will be moved to /docs/

Once the YayDoc generator has been setup correctly, setup.py must copy the docs folder to a known location, and the path must also be updated in PSL_Apps/bin/Experiments .

**Comment by mariobehling** [comment]
Please integrate with Yaydoc and change all html files to MD files now.
