### ISSUE TITLE
Move html to main folder and images to images folder in /docs

### ISSUE THREAD

**Issue by mariobehling** [fossasia/pslab-desktop#175]
The subfolder MD_HTML has lots of file. As a first step to ensure maintanability, please move all html files to the main /docs folder and all images to the image folder.

* https://github.com/fossasia/pslab-desktop-apps/tree/development/docs/MD_HTML/apps

**Comment by jithinbp** [comment]
MD_HTML content is autogenerated by Jekyll. It does not need maintaining. 
When it gets replaced by Yaydoc, I suppose the directory will hold yaydoc output unless yaydoc is included as a dependency, and these files are compiled during the installation process
