### ISSUE TITLE
Unable to run 

### ISSUE THREAD

**Issue by woshikie** [fossasia/pslab-desktop#202]
![2018-06-21-233248_1920x1080_scrot](https://user-images.githubusercontent.com/11439405/41732560-8b4da3b4-75ab-11e8-87f9-59390883c140.png)
Encountered the above problem after running installer script

**Comment by CloudyPadmal** [comment]
Hello @woshikie ! This seems like a PyQt version issue in different Linux flavors. Let me take this up and upgrade the app to `PyQt5`.

**Comment by woshikie** [comment]
Sure thing, I'll work on trying to get it working with the current PyQt

**Comment by cweitat** [comment]
Upgraded to PyQt5 https://github.com/fossasia/pslab-desktop/pull/221
