### ISSUE TITLE
Naming Issues

### ISSUE THREAD

**Issue by woshikie** [fossasia/pslab-desktop#204]
![image](https://user-images.githubusercontent.com/11439405/42387945-83766140-8176-11e8-9c4b-74040240c74a.png)

SQR1/2/3/4 Should be renamed into SQ1/2/3/4. There is no SQR labels on the PSLab and it will confuse users.

Also, please use decimals (".") instead of commas (",") for Phase and Duty Cycle. It is confusing because commas is used for commonly used for counting money (each commas after every 3 digits) while on the PSLab,  in this case, we are handling Duty cycle and Phase of Square Waves, which is an arbitrary unit. Therefore decimals should be used.

**Comment by parammittal16** [comment]
@woshikie can i do this.

**Comment by cweitat** [comment]
dots(".") and commas(",") depends on the region. Some countries in Europe use commas as the decimal separator. For international use, localisation needs to be done.

**Comment by mariobehling** [comment]
Closing as we redesigned the UI.
