### ISSUE TITLE
UI Improvements Needed

### ISSUE THREAD

**Issue by woshikie** [fossasia/pslab-desktop#205]
![image](https://user-images.githubusercontent.com/11439405/42388346-d36dc16a-8177-11e8-8f30-5a104be84964.png)

As you can see in the screenshot above, almost all the controls are using "knobs" while it looks nice on the UI, it is definitely not very user friendly, especially if user has a small screen resolution. Every time I try to move my mouse to turn the knob either turns it too much or too little, it is very hard to fine tune. Perhaps we could add 2 buttons for fine tuning, or make the label into a textbox that is editable.

I am also confused and have some questions regarding the UI: 

1. Why is there only one square function instead of three?
2. Why is square 1 the only one that is all small letters?
3. Why is CAPACITANCE and RESISTANCE all caps while the others are spelled normally?
4. Why does PVs shows "value" instead of their real initial value?
5. What does it mean LOW or HIGH for square 1? Shouldn't it be either 0 Hz (Always Low) or Inf Hz (Always high)?

**Comment by cweitat** [comment]
UI is getting overall revamped so this is out of scope now
