### ISSUE TITLE
Unavailable Experiments

### ISSUE THREAD

**Issue by woshikie** [fossasia/pslab-desktop#207]
![image](https://user-images.githubusercontent.com/11439405/42389394-2b000bd8-817b-11e8-8894-c04f580cbb35.png)

There are some experiments that are unable to be clicked on, instead of disabling the button, I think we should show a pop up to inform the user that the experiment is not available yet, and is coming soon.

**Comment by paltrickontpb** [comment]
Hi @woshikie , I went through all these experiments and i don't seem to find any disabled experiments. Could you tell me which experiments are disabled out for you?
