### ISSUE TITLE
Launch Shortcut for PSLab Desktop Apps

### ISSUE THREAD

**Issue by paltrickontpb** [fossasia/pslab-desktop#217]
For a user friendly application, it will be better if we could open it from a launchbar shortcut like other apps rather than typing in "Experiments" in the console. This is completely aimed towards making the app more user friendly for the public.

**Comment by CloudyPadmal** [comment]
Yes, good idea. You can modify the `installer.sh` script to create a .desktop icon.

**Comment by paltrickontpb** [comment]
Merged and Closed
