### ISSUE TITLE
Migrate to Python 3.7

### ISSUE THREAD

**Issue by orangecms** [fossasia/pslab-desktop#222]
As mentioned in #203, since Python 2 is already deprecated, PSLab Desktop should move forward to Python 3, and 3.4 (currently used in the CI script) is already close to its EOL, so let's go with the current version (3.7). Also see https://devguide.python.org/#status-of-python-branches

**Comment by agarwalrounak** [comment]
I would like to work on this issue. Please assign it to me.

**Comment by mariobehling** [comment]
Just go ahead no need to get assigned. Please make a PR and state the issue in the PR.

**Comment by CloudyPadmal** [comment]
Migrated in #282
