### ISSUE TITLE
Add documentation for installing on Mac

### ISSUE THREAD

**Issue by fragm3** [fossasia/pslab-desktop#230]
Currently, only Linux documentation is present. Add documentation to install pslab-desktop on macbook

**Comment by viragumathe5** [comment]
pslab-desktop is not available for mac os till now

**Comment by ninjapant** [comment]
I would like to work on this.

**Comment by adityastic** [comment]
@ninjapant go ahead

**Comment by ninjapant** [comment]
I'm on it.

**Comment by kumuditha-udayanga** [comment]
I'm working on it

**Comment by adityastic** [comment]
@kumuditha-udayanga sure, go ahead
