### ISSUE TITLE
Implement the settings state in Oscilloscope

### ISSUE THREAD

**Issue by AakashMallik** [fossasia/pslab-desktop#244]
* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request

* **What is the current status?**
The settings UI has been created but the state linking is yet to be done

* **What is the expected behavior?**
The UI should be linked to a state

* **Please tell us about your environment:**
  - OS with version number: Ubuntu 18.04

* **Would you like to work on it?**
@fragm3 will take this issue over...

**Comment by fragm3** [comment]
@AakashMallik on it
