### ISSUE TITLE
Migrate To MUI

### ISSUE THREAD

**Issue by fragm3** [fossasia/pslab-desktop#251]
* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request

* **What is the current status?**
Currently, Antd is used as a component library. If we use antd, we need to eject the app or use rewired-cra for setting dual theme.

* **What is the expected behavior?**
 Use MUI theme instead for dual theme

* **Please tell us about your environment:**
  - OS with version number: macOS 10.14 Mojave

* **Other information** ( Any research that you may have done which you think is the cause of problem )
Link to antd custom theme: https://ant.design/docs/react/customize-theme
Link to MUI theme: https://material-ui.com/customization/themes/#type-light-dark-theme

**Comment by AakashMallik** [comment]
@fragm3 Prioritize this. We can then try out different theme combinations once this has been set up.
