### ISSUE TITLE
Implement Oscilloscope for multi channel

### ISSUE THREAD

**Issue by fragm3** [fossasia/pslab-desktop#258]
* **I'm submitting a ...**
  - [x] bug report
  - [x] feature request

* **What is the current status?**
Currently, oscilloscope is implemented only for 1 channel. Fix for channel 2

* **What is the expected behavior?**
Add channel 2, channel 4 for oscilloscope

* **Please tell us about your environment:**
  - OS with version number: macOS Mojave

* **Would you like to work on it?**
Yes

**Comment by CloudyPadmal** [comment]
Fixed
