### ISSUE TITLE
Electron process still running after closing the app

### ISSUE THREAD

**Issue by ojasgulati** [fossasia/pslab-desktop#314]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request

* **What is the current status?**

     - Electron process after closing still running in the background leaving memory leaks.

* **If the current behavior is a bug, please provide the steps to reproduce it**
> A screenshot of the issue may be sufficient for UI bugs

![Bug_ss](https://files.gitter.im/fossasia/pslab/Wohm/image.png)

* **What is the expected behavior?**
The app should close without leaving any memory leaks 

* **Please tell us about your environment:**
  - OS with version number: [ Windows / OSX / Linux Distro ]
Windows 10 home x64

* **Other information** ( Any research that you may have done which you think is the cause of problem )

* **Would you like to work on it?**
yes

**Comment by AakashMallik** [comment]
@ojasgulati Let add this in the list of discussion on our next meeting. I think it is a good time to address this problem.

**Comment by ojasgulati** [comment]
Sure I will try to gather resources to deal this so we can address this problem more efficiently in the meeting.
