### ISSUE TITLE
UI for Logic Analyser

### ISSUE THREAD

**Issue by ho-dor** [fossasia/pslab-desktop#327]
* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request

* **What is the current status?**
No UI for Logic Analyser instrument

* **If the current behavior is a bug, please provide the steps to reproduce it**
> A screenshot of the issue may be sufficient for UI bugs

N/A

* **What is the expected behavior?**

A UI for Logic Analyser.

* **Please tell us about your environment:**
  - OS with version number: [ Linux Distro ]

* **Other information** ( Any research that you may have done which you think is the cause of problem )

I will use the information from android app to build this.

* **Would you like to work on it?**
Yes

**Comment by AakashMallik** [comment]
@ho-dor Close this issue... PR regarding this has been merged
