### ISSUE TITLE
Power source component freezes if adding a character 'e' in power field

### ISSUE THREAD

**Issue by KSNINJA** [fossasia/pslab-desktop#393]
* **I'm submitting a ...**
  - [x] bug report

* **What is the current status?**
In the power source component, if we try to manually change the power, the field allows us to only add numeric, no characters expect 'e'. On pressing enter, the whole app freezes and then, we have to quit it and start it again.

* Update
The text field allows us to also enter arithmetic operators, which also lead to a crash.

* **If the current behavior is a bug, please provide the steps to reproduce it**
> A screenshot of the issue may be sufficient for UI bugs

![bug](https://user-images.githubusercontent.com/26023139/59978363-2c0dad80-95f9-11e9-9939-209325285b54.gif)

* **What is the expected behavior?**
The field should not accept any letter.

* **Please tell us about your environment:**
  - OS with version number:  OSX 10.14.5

* **Would you like to work on it?**
No

**Comment by AakashMallik** [comment]
@KSNINJA Good job spotting the bug.. check console for error. Also, I think the check function is the culprit here...

**Comment by KSNINJA** [comment]
Sorry,  I am a bit busy for a few days.  Please someone else take up this issue.

**Comment by suyashsingh234** [comment]
Can i take this issue?

**Comment by AakashMallik** [comment]
> Can i take this issue?

Sure @suyashsingh234
