### ISSUE TITLE
React-Rotaty-Knob missing in package.json

### ISSUE THREAD

**Issue by AakashMallik** [fossasia/pslab-desktop#397]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request

* **What is the current status?**
- The package is missing from package.json 

* **What is the expected behaviour?**
- The package should be added to package.json

* **Please tell us about your environment:**
  - OS with version number: Ubuntu 18.04

* **Would you like to work on it?**
No @Deepansharora27 will fix this

**Comment by suyashsingh234** [comment]
I added a pull request which also fixes this bug
