### ISSUE TITLE
Implement Home Screen, Sidebar and Top bar more similarly to Android

### ISSUE THREAD

**Issue by mariobehling** [fossasia/pslab-desktop#404]
Please implement the following similarly to Android in regards to colors, icons, design and functionality:
* top bar
* sidebar
* add missing elements, e.g. white lines
* compare to horizontal view in Android

See missing white lines and tiles. Design does not work as well as on Android due to missing elements. Also: Get more inspiration from Android horizontal view and Windows tiles for example.

![2019_06_26_22_02_49](https://user-images.githubusercontent.com/19551058/60198079-6af06d00-985e-11e9-8ac4-985903a10d91.jpg)

**Comment by AakashMallik** [comment]
Issue addressed. Let me know if you are not satisfied with the results.
