### ISSUE TITLE
Work on python implementation for auto sensor search - I2C

### ISSUE THREAD

**Issue by AakashMallik** [fossasia/pslab-desktop#432]
* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request

* **What is the current status?**
- The python script is not yet functional to scan for sensors

* **What is the expected behaviour?**
- The python script should be functional

* **Please tell us about your environment:**
  - OS with version number: Ubuntu 18.04

* **Would you like to work on it?**
Yes

**Comment by orangecms** [comment]
implemented with #612
