### ISSUE TITLE
Create the pin layout page as that in Android for the Front layout

### ISSUE THREAD

**Issue by AakashMallik** [fossasia/pslab-desktop#480]
* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request

* **What is the current status?**
- only the backlayout has been done so far

* **What is the expected behavior?**
- The frontlayout should also be covered

* **Please tell us about your environment:**
  - OS with version number: Ubuntu 18.04

* **Would you like to work on it?**
Yes

**Comment by rajput2122** [comment]
I want to work on that issue.can you please allow me to proceed

**Comment by AakashMallik** [comment]
> I want to work on that issue.can you please allow me to proceed

Go ahead @rajput2122

**Comment by rajput2122** [comment]
Thanks sir

**Comment by AakashMallik** [comment]
@rajput2122 Take reference from the back layout component. It should be a copy-paste job from there...
