### ISSUE TITLE
Add empty column lat, long etc to the data logger

### ISSUE THREAD

**Issue by AakashMallik** [fossasia/pslab-desktop#497]
* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request

* **What is the current status?**
- The data that cannot be captured using desktop doesn't have a column in CSV

* **What is the expected behaviour?**
- These data columns should still be provided with empty columns.

* **Please tell us about your environment:**
  - OS with version number: Ubuntu 18.04

* **Would you like to work on it?**
No

**Comment by viditkumar** [comment]
Could you please elaborate the above mentioned enhancement? I am interested in picking this up.

**Comment by AakashMallik** [comment]
> Could you please elaborate the above-mentioned enhancement? I am interested in picking this up.

@viditkumar When the user uses the data logger, there are numerous columns that are recorded in a CSV file. When the recording is done in the android app, the latitude and longitude is also recorded, but in the desktop app, we cannot record latitude and longitude. But we still need to put those empty headings from the desktop app.

Shoould be easy enough.

**Comment by AakashMallik** [comment]
> > Could you please elaborate the above-mentioned enhancement? I am interested in picking this up.
> 
> @viditkumar When the user uses the data logger, there are numerous columns that are recorded in a CSV file. When the recording is done in the android app, the latitude and longitude is also recorded, but in the desktop app, we cannot record latitude and longitude. But we still need to put those empty headings from the desktop app.
> 
> Shoould be easy enough.
