### ISSUE TITLE
Home screen alignment needs fixing

### ISSUE THREAD

**Issue by AakashMallik** [fossasia/pslab-desktop#501]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request

* **What is the current status?**
- The home screen alignment uses centre alignment for an odd number of cards.

* **If the current behaviour is a bug, please provide the steps to reproduce it**
![2019_08_24_19_26_28](https://user-images.githubusercontent.com/19551058/63638560-8c77a480-c6a7-11e9-937f-71a134e55aff.jpg)
The robotic arm card is centred and looks weird. 

* **What is the expected behaviour?**
- Left alignment should be used for the odd-numbered card.

* **Please tell us about your environment:**
  - OS with version number: Ubuntu 18.04

* **Would you like to work on it?**
Yes

**Comment by priyanshunayan** [comment]
I want to work on this issue. Can I proceed?

**Comment by AakashMallik** [comment]
> I want to work on this issue. Can I proceed?

Yes, by all means. Go ahead.
