### ISSUE TITLE
Add timebase slider in Logic Analyser

### ISSUE THREAD

**Issue by AakashMallik** [fossasia/pslab-desktop#502]
* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request

* **What is the current status?**
- The user does not have an option to choose between different time bases for logic analyser

* **What is the expected behaviour?**
- A timebase slider should be provided similar to an oscilloscope

* **Please tell us about your environment:**
  - OS with version number: Ubuntu 18.04

* **Would you like to work on it?**
Yes

**Comment by priyanshunayan** [comment]
Can i try this?

**Comment by AakashMallik** [comment]
Sure.. go ahead.. @priyanshunayan . This one should actually be really simple.
The value you are aiming to change using the slider is the sleep value in the logic anaalyser python file.

**Comment by sarthak0906** [comment]
I would like to work on the issue. Can I try?
