### ISSUE TITLE
Fix type in Issue and PR templates 

### ISSUE THREAD

**Issue by AakashMallik** [fossasia/pslab-desktop#504]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request

* **What is the current status?**
- There are typos in the issue and PR templates

* **What is the expected behaviour?**
- Typos need to be fixed 

* **Please tell us about your environment:**
  - OS with version number: Ubuntu 18.04

* **Would you like to work on it?**
Open issue

**Comment by kushthedude** [comment]
@AakashMallik Use tags `good first issue` or `help wanted`, As these tags are read by GitHub to the new contributors in the repository and shown under `collected issues`

**Comment by AakashMallik** [comment]
@kushthedude Point taken

**Comment by priyanshunayan** [comment]
@AakashMallik I am not able to find any typos. I even tested them on grammarly in case I miss any. Can you tell me what's wrong there? I am worried because I have created those files.

**Comment by AakashMallik** [comment]
@priyanshunayan 
typo: behavior 
location: issue_template

**Comment by priyanshunayan** [comment]
@AakashMallik But I have seen 'behavior' in use at multiple places. I have attached the screenshots.  
![image](https://user-images.githubusercontent.com/32892545/63701828-5a02ae80-c843-11e9-83e7-b91d69b805bd.png)
and in google dictionary, in front of "noun":
![behaviour](https://user-images.githubusercontent.com/32892545/63702645-f6798080-c844-11e9-8beb-21184a5c9a03.png)

**Comment by kushthedude** [comment]
@AakashMallik American and British😂

**Comment by AakashMallik** [comment]
> @AakashMallik But I have seen 'behavior' in use at multiple places. I have attached the screenshots.
> ![image](https://user-images.githubusercontent.com/32892545/63701828-5a02ae80-c843-11e9-83e7-b91d69b805bd.png)
> and in google dictionary, in front of "noun":
> ![behaviour](https://user-images.githubusercontent.com/32892545/63702645-f6798080-c844-11e9-8beb-21184a5c9a03.png)
> 
> I think both are used interchangeably.

yup, you are right about that... So should we use American English or British English?

**Comment by mariobehling** [comment]
Ok, thanks for the input. Let's focus on code now. I think we are all clear and can fix typos on the way. Thank you.
