### ISSUE TITLE
Update screenshot layout in README.md and add maintainer section

### ISSUE THREAD

**Issue by AakashMallik** [fossasia/pslab-desktop#507]
* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request

* **What is the expected behaviour?**
- Screenshots need to be improved and put in a tabular form.
- Maintainer section needs to be added

* **Please tell us about your environment:**
  - OS with version number: Ubuntu 18.04

* **Would you like to work on it?**
Yes

**Comment by JoyLubega** [comment]
hey @AakashMallik  can I pick this up?

**Comment by CloudyPadmal** [comment]
Resolved with #508
