### ISSUE TITLE
Make all files in install branch build from dev and master without LFS

### ISSUE THREAD

**Issue by mariobehling** [fossasia/pslab-desktop#512]
Master builds are currently still using LFS. Win images are too big to get build without LFS.

1. Build master images without LFS
2. Investigate, propose and implement ways to reduce the size of the .win image to below 100MB or implement a way to automatically upload the .win image to Dropbox during build using Travis and environment variables.

**Comment by CloudyPadmal** [comment]
Something similar https://medium.com/@baymac/continuous-integration-of-latex-documents-using-travis-ci-a1916c89e978

**Comment by mariobehling** [comment]
First step is to create a dropbox account. Ones things are working this dropbox account can be assigned to FOSSASIA.

**Comment by orangecms** [comment]
no longer applicable - we are using GitHub release attachments now
