### ISSUE TITLE
Wave Generator Font not visible

### ISSUE THREAD

**Issue by mariobehling** [fossasia/pslab-desktop#515]
The text of buttons in the wave generator is not always visible.

![Screenshot from 2019-08-29 05-42-23](https://user-images.githubusercontent.com/1583873/63908545-cc2fea80-ca1f-11e9-8128-3b8e1f289c63.png)

**Comment by AakashMallik** [comment]
This happens when an option is disabled, so for sqr1 user doesn't have an opinion to set phase, that is why it is disabled...
