### ISSUE TITLE
Settings Screen not showing

### ISSUE THREAD

**Issue by mariobehling** [fossasia/pslab-desktop#526]
The settings screen does not show up when the user clicks "Setting".

![Screenshot from 2019-08-29 09-14-49](https://user-images.githubusercontent.com/1583873/63920534-694f4b00-ca41-11e9-822a-5614a9f9061f.png)

**Comment by AakashMallik** [comment]
@mariobehling We don't have any settings to show on Desktop. I'll remove the icon for now

**Comment by AakashMallik** [comment]
I'll be adding a settings page
