### ISSUE TITLE
Home Screen: Show Instrument Tiles in responsive way depending on screen size

### ISSUE THREAD

**Issue by mariobehling** [fossasia/pslab-desktop#533]
Currently the instruments on the home screen are not responsive and show up in two columns. Please change this in a way that depending on the screen size or window width one, two, three or more columns could be displayed. When implementing a responsive way ensure the UI does not get too small to view for the user.
![Screenshot from 2019-08-29 11-11-34](https://user-images.githubusercontent.com/1583873/63927548-3790b100-ca4e-11e9-966d-865eb1116a42.png)

**Comment by imskr** [comment]
I would like to work on this!  Please assign.

**Comment by AakashMallik** [comment]
> I would like to work on this! Please assign.

@imskr Go ahead

**Comment by pushpak1300** [comment]
Can I work On it?

**Comment by imskr** [comment]
@pushpak1300 I'm on it!

**Comment by asha15** [comment]
@imskr Are you working on this?

**Comment by darkthunder007** [comment]
if anyones not working on this , can i?

**Comment by daya2940** [comment]
can i work on this

**Comment by darkthunder007** [comment]
Oh, I also want to work on it...

**Comment by CloudyPadmal** [comment]
@asha15 @darkthunder007 @daya2940 one of you can take this up :+1:

**Comment by asha15** [comment]
Shall i work then?

**Comment by CloudyPadmal** [comment]
@asha15 yes you can :+1:

**Comment by asha15** [comment]
@CloudyPadmal  sir i cannot find the code for the homepage. I'll appreciate of you could help me

**Comment by adityastic** [comment]
@asha15 https://github.com/fossasia/pslab-desktop/blob/development/src/App.js

**Comment by asha15** [comment]
Thank you @adityastic

**Comment by arghac14** [comment]
@mariobehling @AakashMallik @CloudyPadmal is this issue still active, can I work on this?

**Comment by adityastic** [comment]
@arghac14 yes it is

**Comment by arghac14** [comment]
@adityastic can i work on this?

**Comment by adityastic** [comment]
@arghac14 sure, go ahead!

**Comment by ayushiitr2901** [comment]
Is this issue still open, I would like to work on it.

**Comment by NimishGopal** [comment]
I wanna work on this.

**Comment by NitinMadhukar** [comment]
@adityastic can i work on this

**Comment by shivanandaalva** [comment]
Hey,
I would like to work on this
