### ISSUE TITLE
UI fragments/artifacts/pixelation on Home Screen 

### ISSUE THREAD

**Issue by mariobehling** [fossasia/pslab-desktop#535]
The lines connected with the icons in the home screen show fragments or artifacts/pixelation. This is probably due to the graphic formats and limited resolution. For the web it is now possible to use SVG vector graphics, which are small and scalable without loosing any quality. Please research and implement icons as SVGs or find another way to avoid artifacts in the UI.

![Screenshot from 2019-08-29 11-16-12](https://user-images.githubusercontent.com/1583873/63927849-d3bab800-ca4e-11e9-9abc-4e3e4cd74cdb.png)

**Comment by srivastava9** [comment]
Hey Man I am newcomer here.Would like to work on this issue please assign.

**Comment by AakashMallik** [comment]
> Hey Man I am newcomer here.Would like to work on this issue please assign.

Go ahead

**Comment by AakashMallik** [comment]
@srivastava9

**Comment by priyanshunayan** [comment]
@adityastic @mariobehling can I work on this issue?

**Comment by adityastic** [comment]
@priyanshunayan go ahead
