### ISSUE TITLE
Add name of current "screen" on top bar and update Readme.md

### ISSUE THREAD

**Issue by mariobehling** [fossasia/pslab-desktop#545]
The "current activity" name is missing on the top bar of some screens, e.g. Settings and Device page. Please check all screens and ensure they show this on the top bar. Also update the screenshots in the Readme.md, please.

E.g. see settings screen
![settings](https://user-images.githubusercontent.com/1583873/64069584-acc9d500-cc4c-11e9-8b06-02b7be8fb9f6.jpg)

**Comment by AakashMallik** [comment]
Yes.. will make the changes by today. Thanks for testing this.

**Comment by orangecms** [comment]
The PR is merged and the screen do show the titles, so I'm closing this. :)
