### ISSUE TITLE
Home Screen: Don't show "back" button (<-) and Show "Pocket Science Lab - PSLab" in top menu

### ISSUE THREAD

**Issue by mariobehling** [fossasia/pslab-desktop#549]
Please change the home screen as follows:
* don't show <- back button in top menu
* Add text "Pocket Science Lab - PSLab" in top menu bar

![home_screen](https://user-images.githubusercontent.com/1583873/64082225-f2010c00-cd0b-11e9-90d4-2945dcbc33ec.jpg)

**Comment by priyanshunayan** [comment]
Can I work on this issue?
