### ISSUE TITLE
No minimum window size

### ISSUE THREAD

**Issue by pranavkarthik10** [fossasia/pslab-desktop#572]
* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request

* **What is the current status?**
Currently users can resize the window to width and height 0 which would render all content not able to be viewed.

* **If the current behavior is a bug, please provide the steps to reproduce it**
> A screenshot of the issue may be sufficient for UI bugs
<img width="440" alt="Screen Shot 2020-01-03 at 11 26 02 AM" src="https://user-images.githubusercontent.com/44630385/71744369-e0e01d00-2e1b-11ea-8fb0-526348ee74ad.png">

* **What is the expected behavior?**
The minimum width and height should be restricted so all important content can be viewed.

* **Please tell us about your environment:**
  - OS with version number: [ Windows / OSX / Linux Distro ]
OSX 10.15

* **Other information** ( Any research that you may have done which you think is the cause of problem )
This is related to the BrowserWindow class and it's attributes which we must edit to make sure there is minimum size requirements.

* **Would you like to work on it?**
- [x] Yes
- [ ] No

**Comment by cweitat** [comment]
PR #575
