### ISSUE TITLE
chore(tools): add release-drafter.yml inside .github

### ISSUE THREAD

**Issue by snitin315** [fossasia/pslab-desktop#577]
**What is the current status?**
Currently we don't have the `release-drafter.yml` file which is very useful to keep track of a project. As pull requests are merged, a draft release is kept up-to-date listing the changes, ready to publish when you’re ready.
Right Configuration can categorises the changes into headings, and automatically suggests the next version number as well.
for more info [click here](https://github.com/release-drafter/release-drafter)

**Would you like to work on it?**
YES

**Comment by mariobehling** [comment]
low priority. Therefore closing it.
