### ISSUE TITLE
Add a custom menu

### ISSUE THREAD

**Issue by MuhammadWasif** [fossasia/pslab-desktop#583]
* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request

* **What is the current status?**
Menu bar consists of irrelevant menu items. Specially the _help_ menu. It includes the documentation and other links to electronjs. Instead, there should be links to PSLab documentation.
![fjaskldjfa](https://user-images.githubusercontent.com/26650374/72096463-0dc09280-333c-11ea-8929-ba2960a431b4.gif)

* **What is the expected behavior?**
Remove irrelevant options and add help for **PSLab Documentation** 

* **Would you like to work on it?**
Yes

**Comment by mariobehling** [comment]
I recommend to close this PR. Details in PR.

Instead of coming up with additional feature, the app needs to cover the core instruments same as the Android app. Goal is feature parity for now. Thanks.
