### ISSUE TITLE
Deployment on Dropbox

### ISSUE THREAD

**Issue by adityastic** [fossasia/pslab-desktop#586]
We might want to shift our deployment to dropbox as it allows you to store files upto 2GB. At the moment GIT_LFS Only allows us to store files < 100mb. The issue is, we filled our quota already and it would not be relevant to use it for deploying files which are greater than 100mb. 
SideEffects to our repository of using Git-LFS:
* Our Clone Size has increased from some mb's to 1.9gb.

Hence, deploying on GitHub branch is not relevant. Therefore, we should use another service provider like dropbox as discussed.

**Comment by mariobehling** [comment]
This issue is lacking description and does not address the auto-generation of files below 100 MB in the install branch.

**Comment by adityastic** [comment]
@mariobehling updated description

**Comment by mariobehling** [comment]
@adityastic As long as the size is below 100 MB we are fine. Please make a PR where we store the deb file in the install branch. Furthermore please create a Readme with the links to the Dropbox files. There is no need for a snap file currently as it is not working. Thank you!

**Comment by orangecms** [comment]
We have started using GitHub release attachments, so there is no need for extra hosting infrastructure. Closing the issue thusly.
