### ISSUE TITLE
Project not running locally

### ISSUE THREAD

**Issue by Dishebh** [fossasia/pslab-desktop#605]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request

* **What is the current status?**
Currently, the console throws an error:

* **If the current behavior is a bug, please provide the steps to reproduce it**
> A screenshot of the issue may be sufficient for UI bugs
![Screenshot from 2020-01-30 22-50-19](https://user-images.githubusercontent.com/43489708/73473513-ec8b1900-43b2-11ea-908b-7a70f427f272.png)

* **What is the expected behavior?**
The console should be from any errors / warnings. 

* **Please tell us about your environment:**
  - OS with version number: [ Windows / OSX / Linux Distro ]

* **Other information** ( Any research that you may have done which you think is the cause of problem )

* **Would you like to work on it?**
Yes

**Comment by MuhammadWasif** [comment]
The problem is not permanent. Probably, there is an issue in installation of the application. Please consider cloning and installing again. Please Try again. There's no problem with code base.

PS: I also had the same issue but it got solved when I re-installed the app.

**Comment by CloudyPadmal** [comment]
Thank you @MuhammadWasif for pointing out a solution.
