### ISSUE TITLE
logo is showing error:  GET https://docs.pslab.io/_static/ 404

### ISSUE THREAD

**Issue by Ritwik880** [fossasia/pslab-desktop#609]
* **I'm submitting a ...**
  -  bug report
   

* **What is the current status?**
In desktop mode it is not showing such type of logo but as soon as I open in tablet mode the logo is displaying error on the top of the left hand corner.

![Screenshot (18)](https://user-images.githubusercontent.com/54446880/84255950-ea8b5080-ab30-11ea-92c3-230d4654030a.png)

![Screenshot (19)](https://user-images.githubusercontent.com/54446880/84256377-7309f100-ab31-11ea-8eaf-7f341bbc82e1.png)

* **Please tell us about your environment:**
  - OS with version number: Windows

* **Would you like to work on it?**
Yes, I would like to work on it

**Comment by orangecms** [comment]
This issue is part of the docs repository and has been resolved in https://github.com/fossasia/pslab-documentation/pull/121.
