### ISSUE TITLE
load-balancer version update to 3.0.0

### ISSUE THREAD

**Issue by AakashMallik** [fossasia/pslab-desktop#614]
* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request

* **What is the current status?**
@orangecms https://www.npmjs.com/package/electron-load-balancer
I have pushed the updated code to npm. Now 3.0.0 should be a stable dependency for PSL. Let me know if you run into some issues with the new version.

**Comment by orangecms** [comment]
Thanks, done so in `425c0808a3e07025d0215972978de1358c9903ad` :)
