### ISSUE TITLE
set up venv to manage pslab-python dependency

### ISSUE THREAD

**Issue by orangecms** [fossasia/pslab-desktop#638]
Currently, the desktop app is importing `PSL` (https://github.com/fossasia/pslab-python) from the system (or `PYTHONPATH`, that is). For full-stack development and production builds, it would be nice to encapsulate the environment. Python 3 has added native support for environments through `venv`. Implement `venv` for the desktop app.

**Comment by asha15** [comment]
Shall i work on this?

**Comment by orangecms** [comment]
The choice is yours - just file a PR, please. Thank you!

**Comment by cynthi8** [comment]
How could we create a `venv` that works for all production builds? When we package the binaries, we won't know where the python executable is installed on the user's machine.
