### ISSUE TITLE
Setup Github Actions and Substitute Travis CI

### ISSUE THREAD

**Issue by mariobehling** [fossasia/pslab-desktop#652]
Travis CI stopped working. Please substitute Travis with Github Actions.

Also see here: https://github.com/marketplace/actions/electron-builder-action#electron-builder-action

**Comment by orangecms** [comment]
Done, please checks if the builds work for you: See https://github.com/fossasia/pslab-desktop/releases/tag/v2.5.0

**Comment by orangecms** [comment]
I have verified the 2.5.0 tar.gz release to work. \o/

**Comment by cynthi8** [comment]
pslab_2.5.0_amd64.deb works (board connects and basic multimeter tests) on Kubuntu 20.04

**Comment by orangecms** [comment]
Picking up from Gitter: You may need to create a link because PSLab Desktop tries to call `python3` specifically.

- Windows: `mklink python3.exe python.exe` (in the Python install directory)
- UNIX-like systems: `ln -s python python3`

**Comment by orangecms** [comment]
We are at 2.6.0 now and builds are working just fine. Closing this; possible issues can be reported separately.
