### ISSUE TITLE
Python 3 may not be found though installed

### ISSUE THREAD

**Issue by orangecms** [fossasia/pslab-desktop#655]
On some systems, by now, `python` refers to Python 3, while on others, it may refer to Python 2. However, PSLab Desktop only tries to call `python3`.

We need to check the defaults across various systems. Maybe another workaround is necessary. We are using the `python-shell` module. There could be a nice solution by now taking care of pointing to the right version of Python.

**Comment by cynthi8** [comment]
python-shell calls python3 by default [link].(https://github.com/extrabacon/python-shell/blob/f3b64d3307d8dc15eb9c071d8aa774c1e7d5b2d7/index.ts#L94)

**Comment by orangecms** [comment]
Nice, thank you for digging it out! :)

Then we can just remove the explicit option to use `python3`.

It's in https://github.com/fossasia/pslab-desktop/blob/development/background_tasks/linker.html#L10 and the other background task. Could you file a PR? Thanks!

**Comment by cynthi8** [comment]
> Could you file a PR?

Doing it right now!

**Comment by orangecms** [comment]
Can you also confirm that `py` refers to Python 3 on Windows?

https://github.com/extrabacon/python-shell/commit/9baa598beb0a5c8409bf61907a5ec3bc3d176162 looks like that's what they have been calling it for at least two years now. :)

**Comment by cynthi8** [comment]
Yes, I just tested that a few minutes ago ;).
![py_is_the_python_executable_on_windows](https://user-images.githubusercontent.com/71356003/101445388-62271600-38ef-11eb-82d9-daee04f88616.PNG)

**Comment by orangecms** [comment]
Thank you a ton!
