### ISSUE TITLE
No code_of_conduct file is there would like to add

### ISSUE THREAD

**Issue by Sloth-Panda** [fossasia/pslab-desktop#662]
* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request
* **Please tell us about your environment:**
  - OS with version number: [ Windows / OSX / Linux Distro ]
     Windows10

* **Other information** ( Any research that you may have done which you think is the cause of problem )

* **Would you like to work on it?**
Yes

**Comment by cynthi8** [comment]
A link to the [FOSSASIA community guidelines ](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia/) is under the [How to Contribute](https://github.com/fossasia/pslab-desktop#how-to-contribute) section. Is that what you mean?
